image:
  repository: image-registry.openshift-image-registry.svc:5000/openfire-build/openfire-oci
  tag: "4.8.2"
  pullPolicy: Always

routes:
  admin:
    enabled: true
  bosh:
    enabled: true

update:
  serviceEnabled: false
  notifyAdmins: false
  rssEnabled: false

restApi:
  autoEnable: true
  allowWildcardsInExcludes: true
  httpAuth: basic
  serviceLoggingEnabled: false
